### ISSUE TITLE
Roadmap and Pitch Update

### ISSUE THREAD

**Issue by yashpuneet** [cse110-fa22-group28/cse110-fa22-group28#38]
# Administrative or Organizational Tasks

What is the purpose of this task?

To plan out the project deadlines and compile all discussions into the finalized pitch document.

Steps to complete the task:
- [x] Statement of Purpose for Pitch
- [x] Goals for the product in the pitch document
- [x] Create a milestone board for sprint planning
- [x] Finish up sprint planning
- [x] Summarize sprint details in roadmap
